from __future__ import annotations

import json
import shlex
from pathlib import Path, PurePosixPath
from types import SimpleNamespace

import pytest
from langchain_core.messages import ToolMessage

from graphs.build_app_agent_v2.guard_middleware import ToolCallGuardMiddleware
from graphs.build_app_agent_v2.patch_filesystem_middleware import (
    PatchFilesystemMiddleware,
    _resolve_patch_path,
    apply_update_patch,
    parse_patch_content,
)
from graphs.build_app_agent_v2.prompts import build_system_prompt


class _FakeBackend:
    def __init__(
        self,
        files: dict[str, str],
        *,
        fail_upload_for: set[str] | None = None,
    ) -> None:
        self.files = dict(files)
        self.fail_upload_for = set(fail_upload_for or set())

    def download_files(self, paths: list[str]) -> list[SimpleNamespace]:
        responses: list[SimpleNamespace] = []
        for path in paths:
            if path in self.files:
                responses.append(
                    SimpleNamespace(
                        error=None,
                        content=self.files[path].encode("utf-8"),
                    )
                )
            else:
                responses.append(SimpleNamespace(error="file_not_found", content=None))
        return responses

    def upload_files(
        self,
        file_entries: list[tuple[str, bytes]],
    ) -> list[SimpleNamespace]:
        responses: list[SimpleNamespace] = []
        for path, raw_content in file_entries:
            if path in self.fail_upload_for:
                responses.append(
                    SimpleNamespace(error="permission_denied", content=None)
                )
                continue
            self.files[path] = raw_content.decode("utf-8")
            responses.append(SimpleNamespace(error=None, content=None))
        return responses

    def execute(self, cmd: str) -> SimpleNamespace:
        # Supports commands generated by middleware: "rm -f -- <path>".
        tokens = shlex.split(cmd)
        target_path = tokens[-1] if tokens else ""
        self.files.pop(target_path, None)
        return SimpleNamespace(exit_code=0, output="")

    def glob_info(self, pattern: str, path: str = "/") -> list[dict[str, object]]:
        scope = path.rstrip("/") or "/"
        prefix = f"{scope}/" if scope != "/" else "/"
        items: list[dict[str, object]] = []
        for file_path in sorted(self.files):
            if scope == "/":
                in_scope = file_path.startswith("/")
            else:
                in_scope = file_path == scope or file_path.startswith(prefix)
            if not in_scope:
                continue
            rel = file_path[len(prefix) :] if file_path.startswith(prefix) else ""
            rel_path = PurePosixPath(rel or PurePosixPath(file_path).name)
            if rel_path.match(pattern) or PurePosixPath(file_path).match(pattern):
                items.append({"path": file_path, "is_dir": False})
        return items

    async def aglob_info(
        self, pattern: str, path: str = "/"
    ) -> list[dict[str, object]]:
        return self.glob_info(pattern, path)

    def read(self, file_path: str, offset: int = 0, limit: int = 2000) -> str:
        content = self.files.get(file_path)
        if content is None:
            return f"Error: File '{file_path}' not found"
        lines = content.splitlines()
        excerpt = lines[offset : offset + limit]
        start = offset + 1
        return "\n".join(f"{start + i}:{line}" for i, line in enumerate(excerpt))

    async def aread(self, file_path: str, offset: int = 0, limit: int = 2000) -> str:
        return self.read(file_path=file_path, offset=offset, limit=limit)


class _RawReadBackend(_FakeBackend):
    def read(self, file_path: str, offset: int = 0, limit: int = 2000) -> str:
        content = self.files.get(file_path)
        if content is None:
            return f"Error: File '{file_path}' not found"
        lines = content.splitlines()
        return "\n".join(lines[offset : offset + limit])


def test_parse_and_apply_patch_with_multiple_hunks() -> None:
    patch_content = """
*** Update File: style.css
@@ .dark-theme body
 .dark-theme body {
-  color: #ffffff;
+  color: #e0e0e0;
 }
@@ .dark-theme input
 .dark-theme input {
-  background: #fff;
+  background: #222;
 }
""".strip()
    original = """
.dark-theme body {
  color: #ffffff;
}

.dark-theme input {
  background: #fff;
}
""".strip()

    file_patches = parse_patch_content(patch_content)

    assert len(file_patches) == 1
    assert file_patches[0].action == "Update"
    assert file_patches[0].path == "style.css"
    assert len(file_patches[0].hunks) == 2

    updated, applied = apply_update_patch(
        original,
        file_path=file_patches[0].path,
        hunks=file_patches[0].hunks,
    )

    assert applied == 2
    assert "color: #e0e0e0;" in updated
    assert "background: #222;" in updated
    assert "color: #ffffff;" not in updated
    assert "background: #fff;" not in updated


def test_parse_patch_rejects_duplicate_file_sections() -> None:
    patch_content = """
*** Update File: style.css
@@ section-1
-old-1
+new-1
*** Update File: style.css
@@ section-2
-old-2
+new-2
""".strip()

    with pytest.raises(ValueError, match="appears multiple times"):
        parse_patch_content(patch_content)


def test_parse_and_apply_patch_insert_only_hunk() -> None:
    patch_content = """
*** Update File: style.css
@@ insert-muted-color
 .dark-theme body {
+  --muted-text: #a0a0a0;
   color: #ffffff;
 }
""".strip()
    original = """
.dark-theme body {
  color: #ffffff;
}
""".strip()

    file_patches = parse_patch_content(patch_content)
    updated, applied = apply_update_patch(
        original,
        file_path=file_patches[0].path,
        hunks=file_patches[0].hunks,
    )

    assert applied == 1
    assert "--muted-text: #a0a0a0;" in updated
    assert "  color: #ffffff;" in updated


def test_parse_and_apply_patch_insert_only_with_context_after() -> None:
    patch_content = """
*** Update File: style.css
@@ insert-before-closing-brace
+  --surface-contrast: #1a1a1a;
 }
""".strip()
    original = """
.dark-theme body {
  color: #ffffff;
}
""".strip()

    file_patches = parse_patch_content(patch_content)
    updated, applied = apply_update_patch(
        original,
        file_path=file_patches[0].path,
        hunks=file_patches[0].hunks,
    )

    assert applied == 1
    assert "\n  --surface-contrast: #1a1a1a;\n}" in updated
    assert "--surface-contrast: #1a1a1a;" in updated
    assert updated.endswith("\n}")


def test_parse_patch_insert_only_hunk_requires_context() -> None:
    patch_content = """
*** Update File: style.css
@@ insert-without-context
+  --muted-text: #a0a0a0;
""".strip()

    with pytest.raises(ValueError, match="insert-only hunk must include context"):
        parse_patch_content(patch_content)


def test_resolve_patch_path_supports_relative_path_under_workspace() -> None:
    resolved = _resolve_patch_path("src/app.py")
    assert resolved == "/workspace/src/app.py"


def test_resolve_patch_path_rejects_relative_escape() -> None:
    with pytest.raises(ValueError, match="escapes '/workspace'"):
        _resolve_patch_path("../../etc/passwd")


def test_resolve_patch_path_rejects_absolute_path() -> None:
    with pytest.raises(ValueError, match="Absolute patch path"):
        _resolve_patch_path("/workspace/src/app.py")


def test_parse_add_file_requires_plus_prefix() -> None:
    patch_content = """
*** Add File: docs/readme.txt
plain-line
""".strip()

    with pytest.raises(ValueError, match="must start with '\\+'"):
        parse_patch_content(patch_content)


def test_parse_update_hunk_requires_prefix_marker() -> None:
    patch_content = """
*** Update File: style.css
@@ bad-hunk
no-prefix-context
-old
+new
""".strip()

    with pytest.raises(ValueError, match="invalid hunk line prefix"):
        parse_patch_content(patch_content)


def test_apply_patch_sync_supports_move_to() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend({"/workspace/a.py": "x = 1\n"})
    patch_content = """
*** Update File: a.py
*** Move to: b.py
@@ rename-and-edit
-x = 1
+x = 2
""".strip()

    result_raw = middleware._apply_patch_sync(backend, patch_content)
    result = json.loads(result_raw)

    assert result["ok"] is True
    assert "/workspace/a.py" not in backend.files
    assert backend.files["/workspace/b.py"] == "x = 2\n"


def test_patch_filesystem_middleware_replaces_edit_file_tool() -> None:
    middleware = PatchFilesystemMiddleware()
    tool_names = {tool.name for tool in middleware.tools}

    assert "execute" in tool_names
    assert "update_plan" in tool_names
    assert "apply_patch" in tool_names
    assert "get_implementation" not in tool_names
    assert "find_callers" not in tool_names
    assert "read_files" not in tool_names
    assert "list_components" not in tool_names
    assert "read_file" not in tool_names
    assert "write_file" not in tool_names
    assert "ls" not in tool_names
    assert "glob" not in tool_names
    assert "grep" not in tool_names
    assert "edit_file" not in tool_names


def test_guard_extracts_paths_from_apply_patch_payload() -> None:
    guard = ToolCallGuardMiddleware()
    patch_content = """
*** Update File: style.css
@@ section-1
-old
+new
*** Update File: index.html
@@ section-2
-old
+new
""".strip()

    paths = guard._extract_target_paths(
        "apply_patch",
        {"patch_content": patch_content},
    )

    assert paths == ["style.css", "index.html"]


def test_guard_apply_patch_reads_relative_paths_under_workspace_and_attaches_diff(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    guard = ToolCallGuardMiddleware()
    observed_paths: list[str] = []
    contents = iter(["old line\n", "new line\n"])

    def fake_read_file_content(request: object, file_path: str) -> str | None:
        _ = request
        observed_paths.append(file_path)
        return next(contents, None)

    monkeypatch.setattr(guard, "_read_file_content", fake_read_file_content)

    request = SimpleNamespace(
        tool_call={
            "name": "apply_patch",
            "id": "call-1",
            "args": {
                "patch_content": (
                    "*** Begin Patch\n"
                    "*** Update File: app/main.py\n"
                    "@@ update-main\n"
                    "-old line\n"
                    "+new line\n"
                    "*** End Patch"
                )
            },
        },
        state={},
        runtime=SimpleNamespace(),
    )

    def handler(_request: object) -> ToolMessage:
        return ToolMessage(content="ok", tool_call_id="call-1")

    result = guard.wrap_tool_call(request, handler)

    assert observed_paths == ["/workspace/app/main.py", "/workspace/app/main.py"]
    assert isinstance(result, ToolMessage)
    assert result.additional_kwargs["file_diff"]["file_path"] == "app/main.py"


def test_guard_ls_budget_blocks_repeated_same_path() -> None:
    guard = ToolCallGuardMiddleware(
        max_ls_calls_total=5,
        max_ls_calls_per_path_total=1,
    )
    state: dict[str, object] = {}

    first = guard._enforce_ls_budget(
        args={"path": "/workspace"},
        state=state,
        tool_call_id="call-1",
    )
    assert first is None
    assert state["ls_calls_total"] == 1

    blocked = guard._enforce_ls_budget(
        args={"path": "/workspace"},
        state=state,
        tool_call_id="call-2",
    )
    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked repeated ls" in str(blocked.content)


def test_guard_ls_budget_blocks_total_ls_calls() -> None:
    guard = ToolCallGuardMiddleware(
        max_ls_calls_total=1,
        max_ls_calls_per_path_total=5,
    )
    state: dict[str, object] = {}

    first = guard._enforce_ls_budget(
        args={"path": "/workspace"},
        state=state,
        tool_call_id="call-1",
    )
    assert first is None

    blocked = guard._enforce_ls_budget(
        args={"path": "/workspace/src"},
        state=state,
        tool_call_id="call-2",
    )
    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked ls due to discovery-call budget" in str(blocked.content)


def test_guard_ls_budget_blocks_repeated_subtree_walk() -> None:
    guard = ToolCallGuardMiddleware(
        max_ls_calls_total=10,
        max_ls_calls_per_path_total=10,
        max_ls_calls_per_root_total=2,
    )
    state: dict[str, object] = {}

    first = guard._enforce_ls_budget(
        args={"path": "/workspace/packages/components/src"},
        state=state,
        tool_call_id="call-1",
    )
    assert first is None

    second = guard._enforce_ls_budget(
        args={"path": "/workspace/packages/components/src/search"},
        state=state,
        tool_call_id="call-2",
    )
    assert second is None

    blocked = guard._enforce_ls_budget(
        args={"path": "/workspace/packages/components/src/search/src"},
        state=state,
        tool_call_id="call-3",
    )
    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked ls subtree walk under '/workspace/packages/components/src'" in str(
        blocked.content
    )


def test_guard_glob_budget_blocks_root_path() -> None:
    guard = ToolCallGuardMiddleware()
    state: dict[str, object] = {}

    blocked = guard._enforce_glob_budget(
        discovery_tool_name="glob",
        args={"path": "/", "pattern": "**/*.py"},
        state=state,
        tool_call_id="call-glob-root",
    )

    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked glob on '/'" in str(blocked.content)


def test_guard_glob_budget_blocks_broad_pattern() -> None:
    guard = ToolCallGuardMiddleware()
    state: dict[str, object] = {}

    blocked = guard._enforce_glob_budget(
        discovery_tool_name="glob",
        args={"path": "/workspace", "pattern": "**/*"},
        state=state,
        tool_call_id="call-glob-broad",
    )

    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked broad glob pattern" in str(blocked.content)


def test_guard_glob_budget_blocks_repeated_same_path() -> None:
    guard = ToolCallGuardMiddleware(
        max_glob_calls_total=5,
        max_glob_calls_per_path_total=1,
    )
    state: dict[str, object] = {}

    first = guard._enforce_glob_budget(
        discovery_tool_name="glob",
        args={"path": "/workspace/app", "pattern": "**/*.py"},
        state=state,
        tool_call_id="call-glob-1",
    )
    assert first is None
    assert state["glob_calls_total"] == 1

    blocked = guard._enforce_glob_budget(
        discovery_tool_name="glob",
        args={"path": "/workspace/app", "pattern": "**/*.ts"},
        state=state,
        tool_call_id="call-glob-2",
    )
    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked repeated glob for '/workspace/app'" in str(blocked.content)


def test_guard_glob_budget_blocks_total_calls() -> None:
    guard = ToolCallGuardMiddleware(
        max_glob_calls_total=1,
        max_glob_calls_per_path_total=5,
    )
    state: dict[str, object] = {}

    first = guard._enforce_glob_budget(
        discovery_tool_name="glob",
        args={"path": "/workspace/app", "pattern": "**/*.py"},
        state=state,
        tool_call_id="call-glob-1",
    )
    assert first is None

    blocked = guard._enforce_glob_budget(
        discovery_tool_name="glob",
        args={"path": "/workspace/tests", "pattern": "**/*.py"},
        state=state,
        tool_call_id="call-glob-2",
    )
    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked glob due to discovery-call budget" in str(blocked.content)


def test_guard_list_resources_uses_scope_pattern_budget_mapping() -> None:
    guard = ToolCallGuardMiddleware()

    mapped = guard._build_discovery_glob_args(
        tool_name="list_resources",
        args={"scope": "/workspace/app", "pattern": "**/*.py"},
    )

    assert mapped == {"path": "/workspace/app", "pattern": "**/*.py"}


def test_guard_list_resources_budget_blocks_root_scope() -> None:
    guard = ToolCallGuardMiddleware()
    state: dict[str, object] = {}

    blocked = guard._enforce_glob_budget(
        discovery_tool_name="list_resources",
        args={"path": "/", "pattern": "**/*.py"},
        state=state,
        tool_call_id="call-list-res-root",
    )

    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked list_resources on '/'" in str(blocked.content)


def test_guard_list_resources_budget_blocks_broad_pattern() -> None:
    guard = ToolCallGuardMiddleware()
    state: dict[str, object] = {}

    blocked = guard._enforce_glob_budget(
        discovery_tool_name="list_resources",
        args={"path": "/workspace", "pattern": "**/*"},
        state=state,
        tool_call_id="call-list-res-broad",
    )

    assert blocked is not None
    assert blocked.status == "error"
    assert "Blocked broad list_resources pattern" in str(blocked.content)


def test_build_system_prompt_uses_single_template() -> None:
    prompt = build_system_prompt()

    assert "你是一个编码代理" in prompt
    assert "## `apply_patch`" in prompt


def test_guard_blocks_write_before_submit_plan() -> None:
    guard = ToolCallGuardMiddleware(require_plan_before_write=True)
    state: dict[str, object] = {}

    blocked = guard._enforce_plan_for_write(
        tool_name="apply_patch",
        target_paths=["/workspace/style.css"],
        state=state,
        tool_call_id="call-1",
    )

    assert blocked is not None
    assert blocked.status == "error"
    assert "call `submit_edit_plan` first" in str(blocked.content)


def test_guard_accepts_write_after_submit_plan_for_declared_file() -> None:
    guard = ToolCallGuardMiddleware(require_plan_before_write=True)
    state: dict[str, object] = {}

    recorded = guard._record_submit_edit_plan(
        args={
            "plan_summary": "Update dark theme colors",
            "target_files": ["/workspace/style.css"],
        },
        state=state,
        tool_call_id="call-plan",
    )
    assert recorded is None

    blocked = guard._enforce_plan_for_write(
        tool_name="apply_patch",
        target_paths=["/workspace/style.css"],
        state=state,
        tool_call_id="call-write",
    )
    assert blocked is None


def test_guard_blocks_write_for_file_outside_submitted_plan() -> None:
    guard = ToolCallGuardMiddleware(require_plan_before_write=True)
    state: dict[str, object] = {}

    recorded = guard._record_submit_edit_plan(
        args={
            "plan_summary": "Update css only",
            "target_files": ["/workspace/style.css"],
        },
        state=state,
        tool_call_id="call-plan",
    )
    assert recorded is None

    blocked = guard._enforce_plan_for_write(
        tool_name="apply_patch",
        target_paths=["/workspace/index.html"],
        state=state,
        tool_call_id="call-write",
    )
    assert blocked is not None
    assert blocked.status == "error"
    assert "was not declared in `submit_edit_plan.target_files`" in str(blocked.content)


def test_apply_patch_sync_supports_dry_run_without_writing_files() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend({"/workspace/a.py": "x = 1\n"})
    patch_content = """
*** Update File: a.py
@@ update-a
-x = 1
+x = 2
""".strip()

    result_raw = middleware._apply_patch_sync(
        backend,
        patch_content,
        dry_run=True,
    )
    result = json.loads(result_raw)

    assert result["ok"] is True
    assert result["details"]["phase"] == "dry_run"
    assert backend.files["/workspace/a.py"] == "x = 1\n"


def test_apply_patch_sync_rolls_back_on_mid_commit_failure() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend(
        {
            "/workspace/a.py": "x = 1\n",
            "/workspace/b.py": "y = 1\n",
        },
        fail_upload_for={"/workspace/b.py"},
    )
    patch_content = """
*** Update File: a.py
@@ update-a
-x = 1
+x = 2
*** Update File: b.py
@@ update-b
-y = 1
+y = 2
""".strip()

    result_raw = middleware._apply_patch_sync(backend, patch_content)
    result = json.loads(result_raw)

    assert result["ok"] is False
    assert result["error_code"] == "PATCH_PARTIAL_FORBIDDEN"
    assert result["details"]["failed_path"] == "/workspace/b.py"
    assert backend.files["/workspace/a.py"] == "x = 1\n"
    assert backend.files["/workspace/b.py"] == "y = 1\n"


def test_list_resources_returns_file_uris() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend(
        {
            "/workspace/app/main.py": "print('main')\n",
            "/workspace/app/utils.py": "print('utils')\n",
            "/workspace/tests/test_main.py": "assert True\n",
        }
    )

    result_raw = middleware._list_resources_sync(
        backend=backend,
        scope="/workspace/app",
        pattern="**/*.py",
        resource_kind="file",
        limit=10,
    )
    result = json.loads(result_raw)

    assert result["ok"] is True
    items = result["details"]["items"]
    assert len(items) == 2
    assert all(item["kind"] == "file" for item in items)
    assert all(item["uri"].startswith("file:///workspace/app/") for item in items)


def test_read_resource_supports_file_uri() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend({"/workspace/app/main.py": "print('main')\n"})

    result_raw = middleware._read_resource_sync(
        backend=backend,
        uri="file:///workspace/app/main.py",
        offset=0,
        limit=20,
    )
    result = json.loads(result_raw)

    assert result["ok"] is True
    assert result["details"]["path"] == "/workspace/app/main.py"
    assert "print('main')" in result["details"]["content"]


def test_read_resource_supports_percent_encoded_file_uri_path() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend({"/workspace/app/main file.py": "print('main')\n"})

    result_raw = middleware._read_resource_sync(
        backend=backend,
        uri="file:///workspace/app/main%20file.py",
        offset=0,
        limit=20,
    )
    result = json.loads(result_raw)

    assert result["ok"] is True
    assert result["details"]["path"] == "/workspace/app/main file.py"
    assert "print('main')" in result["details"]["content"]


def test_read_resource_does_not_treat_plain_error_prefixed_content_as_failure() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _RawReadBackend(
        {"/workspace/app/messages.txt": "Error: expected input format\nsecond line\n"}
    )

    result_raw = middleware._read_resource_sync(
        backend=backend,
        uri="file:///workspace/app/messages.txt",
        offset=0,
        limit=20,
    )
    result = json.loads(result_raw)

    assert result["ok"] is True
    assert "Error: expected input format" in result["details"]["content"]


def test_read_resource_supports_symbol_uri() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend(
        {
            "/workspace/app/service.py": (
                "class OrderService:\n    def run(self) -> str:\n        return 'ok'\n"
            )
        }
    )

    result_raw = middleware._read_resource_sync(
        backend=backend,
        uri="symbol://OrderService?path=/workspace/app/service.py&start=1&end=6",
        offset=0,
        limit=6,
    )
    result = json.loads(result_raw)

    assert result["ok"] is True
    assert result["details"]["resource_type"] == "symbol"
    assert result["details"]["symbol"] == "OrderService"
    assert "OrderService" in result["details"]["content"]


def test_read_resource_rejects_unsupported_scheme() -> None:
    middleware = PatchFilesystemMiddleware()
    backend = _FakeBackend({"/workspace/app/main.py": "print('main')\n"})

    result_raw = middleware._read_resource_sync(
        backend=backend,
        uri="http://example.com/resource.py",
        offset=0,
        limit=20,
    )
    result = json.loads(result_raw)

    assert result["ok"] is False
    assert result["error_code"] == "RESOURCE_SCHEME_UNSUPPORTED"


def test_agent_graph_defines_explicit_plan_act_stategraph() -> None:
    source = Path("graphs/build_app_agent_v2/agent.py").read_text(encoding="utf-8")

    assert "StateGraph(" in source
    assert 'builder.add_node("plan"' in source
    assert 'builder.add_node("act"' in source
    assert 'builder.add_edge("plan", "act")' in source
    assert 'blocked_tools = {"apply_patch", "write_file", "execute"}' in source
